### ISSUE TITLE
建议加入功能

### ISSUE THREAD

**Issue by roughanddai** [Polar-Pumpkin/Shoal#2]
- 能否加入一个可显示目前所有正在进行的投票的功能  

- 在config文件中加入一个最低通过人数限制，最低反对人数限制，这样可以避免设定1人通过导致投票无意义（没测试行不行，理论可以）

- 加入一个查看所有正在进行的投票的快捷指令

- 加入一个玩家加入时提醒玩家什么投票正在进行的功能

- 加入一个查看我自己的正在进行的快捷指令

- 能否在config文件中设定正在投票的反对和同意可以在玩家投票完后公示

- 加入一个指令白名单，这个不用解释了吧

- 加入一个可自己设定id的功能，

**Comment by Polar-Pumpkin** [comment]
# 鸭！感谢你的提议！
- - -
其实看看上一个 Issue (#1) ，倒数第二个特性已经有了（应该和你想的一样吧），只是我没在MCBBS发布更新，你可以在 Github 项目的 Release 页面下载到具有此特性的 v1.4 版本。

但是这个版本对于投票 ID 的改动可能还有其他未被发现的影响，如果你发现了 Bug 一定要赶快反馈！我会尽快修的。

说个未来的计划，当前版本的代码是早期的写的，我感觉好烂啊，可维护性有点差。我已经学习了很多更简单的更好的解决方案，所以是打算重写 VoteUp 的，就是 2.0。不过新功能也会添加，Bug 也会修复的。但是我现在刚好高三下准备高考，可能没有那么多时间能够立即对新功能的建议和 Bug 反馈回应和及时修复，抱歉qwq。
- - -
**感谢你使用 VoteUp 和积极提供建议！awa**

**Comment by roughanddai** [comment]
我好像没找到config里面关于whitelist的，能否请教怎么用
增加建议
- 支持使用权限树来配置指令，例如限制gamemode.*权限树下的指令使用，这样可以更加精确的配置指令使用，甚至有更多可能

**Comment by Polar-Pumpkin** [comment]
> 我好像没找到config里面关于whitelist的，能否请教怎么用

好像我在 Release 的更新日志上写了，关于这个功能的更多信息可以看看我们在 #1 的讨论。

具体就是，当`BlackMode`启用时，下方的`List`配置内容将变为黑名单，即：
玩家在投票的Autocast(自动执行)中设定的内容包含黑名单中的指令时，将无法保存。
具体为判断指令头部，即首个指令关键词。

当该选项禁用时，为白名单模式，只有配置的内容中的指令才可被设置为Autocast的内容。

> * 支持使用权限树来配置指令，例如限制gamemode.*权限树下的指令使用，这样可以更加精确的配置指令使用，甚至有更多可能

需要更多信息。关于 VoteUp 2 的重置进度已开始，你可以在`voteup2`分支中查看进度。

**Comment by Polar-Pumpkin** [comment]
> 能否在config文件中设定正在投票的反对和同意可以在玩家投票完后公示

需要更多信息。关于 VoteUp 2 的重置进度已进行了一段时间，你可以在`voteup2`分支中查看进度。
以及，如果能参与 VoteUp 2 的测试，那当然是极好的. :3

**Comment by roughanddai** [comment]
new建议

- 可以在投票的那个自动执行上明示白名单可以执行的命令吗？（虽然我知道直接改文件也可以办到）

**Comment by roughanddai** [comment]
> > 能否在config文件中设定正在投票的反对和同意可以在玩家投票完后公示
> 
> 需要更多信息。关于 VoteUp 2 的重置进度已进行了一段时间，你可以在`voteup2`分支中查看进度。
> 以及，如果能参与 VoteUp 2 的测试，那当然是极好的. :3

描述一下：在聊天框内显示xxxx投票通过，可以设定一个占位符，开投票的人点击后可以查看 同意：xxxx|xxx 反对：xxxxxx|xx  
例如：  
我今天中午吃饭投票通过（点击此处查看详细）  
点击后聊天框显示：同意：用户id 反对：用户id

**Comment by Polar-Pumpkin** [comment]
> new建议
> 
> 
> 
> - 可以在投票的那个自动执行上明示白名单可以执行的命令吗？（虽然我知道直接改文件也可以办到）

啊啊，我感觉无法理解，是需要在Gui中显示出配置文件内的白名单内容，还是能在游戏内添加白名单条目？

**Comment by Polar-Pumpkin** [comment]
> > > 能否在config文件中设定正在投票的反对和同意可以在玩家投票完后公示
> 
> > 
> 
> > 需要更多信息。关于 VoteUp 2 的重置进度已进行了一段时间，你可以在`voteup2`分支中查看进度。
> 
> > 以及，如果能参与 VoteUp 2 的测试，那当然是极好的. :3
> 
> 
> 
> 描述一下：在聊天框内显示xxxx投票通过，可以设定一个占位符，开投票的人点击后可以查看 同意：xxxx|xxx 反对：xxxxxx|xx  
> 
> 例如：  
> 
> 我今天中午吃饭投票通过（点击此处查看详细）  
> 
> 点击后聊天框显示：同意：用户id 反对：用户id

大概了解了，会有一个界面能够展示出所有参与者及其所选的选项。

**Comment by roughanddai** [comment]
> > new建议
> > 
> > * 可以在投票的那个自动执行上明示白名单可以执行的命令吗？（虽然我知道直接改文件也可以办到）
> 
> 啊啊，我感觉无法理解，是需要在Gui中显示出配置文件内的白名单内容，还是能在游戏内添加白名单条目？

算是在悬浮列表上显示吧`MODIFY_AUTOCAST:
    ItemStack:
      Display: "自动执行"
      Material: COMMAND_BLOCK
      Lore:
        - ""
        - "&9▶ &7当前内容:"
        - "&8▶ &a%AUTOCAST%"
        - ""
        - "&a▶ &7&o单击以编辑自动执行命令"
      ItemFlag:
        - "HIDE_ATTRIBUTES"
    Position:
      X: 8
      Y: 1
    ViewPermission: "VoteUp.create.autocast"`
在guiscfg这一段的悬浮菜单里面可以显示一下目前可用的命令吗？

**Comment by Polar-Pumpkin** [comment]
我day到了！会做哒

**Comment by roughanddai** [comment]
顺带一提，如果VOTEUP 2.0支持1.15.2的服务端的话可以试试

**Comment by Polar-Pumpkin** [comment]
已经快重写完成了，与先前的1.4版本相比只差一个具体的投票操作了，比如打开“投票详细信息”页面按按钮参与投票。

VoteUp 基于1.14.4构建，理论上应该支持1.15.2，只需要尝试在此版本构建一次，然后看看有没有错误出现就行了。

**Comment by Polar-Pumpkin** [comment]
经过我刚刚的快速测试，VoteUp 2(包括 VoteUp 1.4)能在1.15.2下运行。
也许等我再写一些功能我就会放出截图(饼)出来看看了。;3
现在就是需要写很多Gui。

**Comment by Polar-Pumpkin** [comment]
归纳整理一下你提出的功能建议。
- [x] 能否加入一个可显示目前所有正在进行的投票的功能
  - 已经在 VoteUp v2.0.5-Beta 中添加，使用 `/votes search open` 指令快捷检索所有正在进行的投票，标准写法：`/votes search open:true`。
- [x] 在config文件中加入一个最低通过人数限制，最低反对人数限制，这样可以避免设定1人通过导致投票无意义（没测试行不行，理论可以）
  - 已经在 VoteUp v2.0-Beta 中添加，具体为最低参与人数要求，低于此参与人数，就算符合对应投票类型的要求，仍然无法通过投票。
- [x] 加入一个查看所有正在进行的投票的快捷指令
  - 已经在 VoteUp v2.0.5-Beta 中添加，使用 `/votes search open` 指令快捷检索所有正在进行的投票，标准写法：`/votes search open:true`。
- [x] 加入一个玩家加入时提醒玩家什么投票正在进行的功能
  - 已经在 VoteUp v2.0.1-Beta 中添加。具体为玩家加入时获取正在进行中的最新投票发送通知。
- [x] 加入一个查看我自己的正在进行的快捷指令
  - 已经在 VoteUp v2.0.5-Beta 中添加，使用 `/votes search me` 指令快捷检索所有由本人发起的投票，标准写法：`/votes search owner:<本人ID>`。
- [ ] 能否在config文件中设定正在投票的反对和同意可以在玩家投票完后公示
- [x] 加入一个可自己设定id的功能
  - 已经在 VoteUp v2.0-Beta 中添加。
- [x] 加入一个指令白名单，这个不用解释了吧
  - 已经在 VoteUp v1.4.3-Release 中添加。
- [x] 可以在投票的那个自动执行上明示白名单可以执行的命令吗？（虽然我知道直接改文件也可以办到）
  - 已经在 VoteUp v2.0.1-Beta 中添加。
- [x] 支持使用权限树来配置指令，例如限制 `gamemode.*` 权限树下的指令使用，这样可以更加精确的配置指令使用，甚至有更多可能
  - 已经在 VoteUp v2.0.1-Beta 中添加。具体为以玩家身份执行指令，玩家自己可以手动执行的指令（在投票结束时在线）就可以由自动执行来执行，当玩家不在线时会缓存，等到玩家上线时自动执行。

其余功能建议即将到来。^^

感谢您使用并支持 VoteUp。

**Comment by Polar-Pumpkin** [comment]
对于这个功能：

> 支持使用权限树来配置指令，例如限制gamemode.*权限树下的指令使用，这样可以更加精确的配置指令使用，甚至有更多可能

大概可以理解为，以发起者玩家的权限身份来执行自动执行的命令内容吧，这样玩家没有权限就不能执行力。

**Comment by roughanddai** [comment]
> 对于这个功能：
> 
> > 支持使用权限树来配置指令，例如限制gamemode.*权限树下的指令使用，这样可以更加精确的配置指令使用，甚至有更多可能
> 
> 大概可以理解为，以发起者玩家的权限身份来执行自动执行的命令内容吧，这样玩家没有权限就不能执行力。

差不多这个意思，通过联动groupmanage的权限来执行

**Comment by Polar-Pumpkin** [comment]
对于这个功能：
> 能否在config文件中设定正在投票的反对和同意可以在玩家投票完后公示

需要更多信息，有点不太懂什么意思。

> 投票进度/结果公开 [Issue #2]
能否在config文件中设定正在投票的反对和同意可以在玩家投票完后公示
投票进度公开后，任何玩家都可以在该投票的详细信息界面查看当前的投票参与者列表，及其看法与投票选项。且在玩家投票后立刻全服通知。
投票结果公开后，全服玩家都可以在投票结束后收到通知信息。（当前设计应该是拥有提醒权限(VoteUp.notice)或投票发起人可以在投票结束后收到投票结果的通知信息，且当目标玩家不在线时通知被挂起）

我当初这么想的[Issue #3]，但是太久没开这个项目了(一个月前)，我全都忘了... 自己都看不懂了

**Comment by roughanddai** [comment]
> 对于这个功能：
> 
> > 能否在config文件中设定正在投票的反对和同意可以在玩家投票完后公示
> 
> 需要更多信息，有点不太懂什么意思。
> 
> > 投票进度/结果公开 [Issue #2]
> > 能否在config文件中设定正在投票的反对和同意可以在玩家投票完后公示
> > 投票进度公开后，任何玩家都可以在该投票的详细信息界面查看当前的投票参与者列表，及其看法与投票选项。且在玩家投票后立刻全服通知。
> > 投票结果公开后，全服玩家都可以在投票结束后收到通知信息。（当前设计应该是拥有提醒权限(VoteUp.notice)或投票发起人可以在投票结束后收到投票结果的通知信息，且当目标玩家不在线时通知被挂起）
> 
> 我当初这么想的[Issue #3]，但是太久没开这个项目了(一个月前)，我全都忘了... 自己都看不懂了

老项目了
