### ISSUE TITLE
1.16.1 说需要前置??

### ISSUE THREAD

**Issue by Akizon77** [Polar-Pumpkin/Shoal#5]
[Server thread/ERROR]: Could not load 'plugins/VoteUp-2.0.3-BETA.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: Unknown dependency ParrotX. Please download and install ParrotX to run this plugin.

[Server thread/INFO]: Plugins (4): CoreProtect, Skript, GroupManager, TabooSK

**Comment by Polar-Pumpkin** [comment]
VoteUp 2 开始使用我写的插件前置核心 ParrotX，在v2.0-Beta和v2.0.3-Beta的Release更新中都有提供下载喔。

**Comment by Akizon77** [comment]
谢谢,可能是我瞎了叭

**Comment by Polar-Pumpkin** [comment]
没关系，感谢使用与支持 VoteUp。:3

**Comment by Akizon77** [comment]
晚安,这么晚了还在回答我的弱智问题qwq

**Comment by Polar-Pumpkin** [comment]
晚安，放学回家想修点 Bug，要是有时间添加新功能那就更好了，我也一直尽力做到最快速度回复 Issue 和修复 Bug。^w^
