### ISSUE TITLE
在spigot-1.16.1有一些问题

### ISSUE THREAD

**Issue by Akizon77** [Polar-Pumpkin/Shoal#6]
### 在spigot端
* 指令无任何反应(一开始会报错后来插件就相当于被卸载了?)
### 在paper端
* 插件无法加载并且会被强制卸载
---
https://github.com/Hytf233/cdn/blob/master/Issues/20200701/readme.md

**Comment by Polar-Pumpkin** [comment]
很抱歉过了这么久才回复，因为在上晚修。
今天1点左右更新的v2.0.4-Beta版本修复了大量 Bug，其中包括如日志反馈显示的加载投票数据文件出现错误的问题，建议更新一下。
